export const REVERSE_IMAGE_PROPS = {
  Title: "Enhance Your SEO Strategy with DevAxon's Reverse Image Search Tool",
  Description: `The importance of photos in SEO cannot be overemphasized in the wide world of digital marketing and content development. Professionals and digital marketers now have an effective tool at their disposal to improve their SEO strategy and increase their online visibility: DevAxon's Reverse Image Search tool. The advantages and features of using this cutting-edge technology to improve your SEO results through strategic picture optimization are explained in this post.`,
  Img1: "/img/Remove1.png",
  Heading1: "Revolutionizing Image Optimization",
  Description1: `DevAxon's Reverse Image Search tool is the ultimate solution for meeting the intricate needs of SEO optimization. With its ability to track the source of images, evaluate their usage on the internet, and find related images, this tool has become the go-to option for optimizing digital content. It's an indispensable tool that ensures your photos are original and relevant, and it significantly boosts your search engine optimization. Opt for DevAxon's Reverse Image Search tool today and take your SEO optimization game to the next level!`,
  Img2: "/img/Remove2.png",
  Heading2: "Key Features of the Reverse Image Search Tool",
  subHeading1: "Competitive Analysis:",
  subHeadingDescription1: `Conduct a competitive analysis to understand how rivals use photos in content strategy. Understanding the visual cues that appeal to your target market can help you adjust your strategy to both meet and exceed industry standards.`,
  subHeading2: "Identify Duplicate Content:",
  subHeadingDescription2: `This tool helps you find out where and how your photos are being utilized on the internet. This is essential to safeguarding the uniqueness of your material and avoiding search engine penalties related to duplicate content.`,
  subHeading3: "Enhance Content Authenticity:",
  subHeadingDescription3: `To ensure the credibility of the photos on your website or blog, utilizing the reverse image search is a must. This not only enhances audience trust but also boosts your SEO rankings.`,
  subHeading4: "Link Building Opportunities:",
  subHeadingDescription4: `One way to build links to your website is by identifying websites that are using your photographs without proper credit. By reaching out to the website owner and requesting that they provide a link back to your website, you can potentially improve your website's authority and performance in search engine results. This approach can be an effective strategy for link-building and increasing your website's visibility.`,
  Img3: "/img/Remove3.png",
  Img4: "/img/Remove4.png",
  Heading3: "How to Use DevAxon's Reverse Image Search Tool?",
  subHeading5: "Access the Tool:",
  subHeadingDescription5: `Visit the SEO Tools section on your DevAxon website and locate the Reverse Image Search tool.`,
  subHeading6: "Upload Image:",
  subHeadingDescription6: `You can either upload the image directly from your device or simply drag & drop the image you wish to search for.`,
  subHeading7: "Initiate Search:",
  subHeadingDescription7: `Once the image is uploaded, the tool automatically initializes its process of analyzing the image and gives the results from different search engines. The tool will promptly display a list of websites using the image, along with similar images found across the web. Use this information to enhance your SEO strategy and content uniqueness.`,
};
export const SPLIT_TOOL_PROPS = {
  backgroundImage: "/img/Rectangle24.png",
  logoImage: "/img/Split.png",
  toolName: "Split Pdf",
  toolSpec: " Split PDF",
  bgColor: "bg-[#DBF3F2]",
  apiEndpoint: "/api/splitPdf",
  BtnName: "Select PDF File",
  acceptedFiles: "application/pdf",
  Title: "Divide and Conquer with Our Split PDF Tool",
  Description: `Introducing Split PDF Tool by DevAxon, the ultimate destination for cutting-edge SEO tools that will improve your online experience. We're excited to present our Split PDF tool today, a potent tool that enables users to effectively divide big PDF files into smaller, more manageable parts. Bid farewell to cumbersome paperwork and welcome to efficient structure.`,
  Img1: "/img/Split1.png",
  Heading1: "Why Use Our Split PDF Tool?",
  Description1: `Working with large PDF files can be difficult, especially if you just need to access certain pages or portions. This problem is resolved by our Split PDF tool, which offers an easy-to-use method for splitting PDFs into more manageable, targeted sections. This reduces needless load times, which enhances website speed in addition to helping with content structure.`,
  Img2: "/img/Split2.png",
  Heading2: "Key Features:",
  subHeading1: "Accurate PDF Splitting:",
  subHeadingDescription1: `With the help of our program, you can easily extract individual pages or choose certain pages or ranges of pages. You may be confident that you will only keep the sections of the document that are pertinent to your requirements with this degree of modification.`,
  subHeading2: "Interface That's Easy to Use:",
  subHeadingDescription2: `Discover the ease of use of our intuitive UI. Our Split PDF tool is easy to use and can be used by both novices and experts alike, making it a joy to divide PDF files.`,
  subHeading3: "Using Batch Processing to Increase Efficiency:",
  subHeadingDescription3: `You must divide many PDFs at once. Not an issue. Because of the batch processing capabilities of our program, you may divide numerous files at once effectively and quickly, saving you a great deal of time and work.`,
  subHeading4: "The Maintenance of Document Quality:",
  subHeadingDescription4: ` You can be confident that your documents' quality will be preserved during the splitting process by using our Split PDF tool. Every section that is extracted will reflect the accuracy and clarity of the original PDF.`,
  Img3: "/img/Split3.png",
  Img4: "/img/Split4.png",
  Heading3: "How to Use Our Split PDF Tool?",
  subHeading5: "Put Your PDF File Here:",
  subHeadingDescription5: `Choose the PDF file that you want to split first. Our tool offers versatility for a range of applications by supporting files of varying sizes.`,
  subHeading6: "Initialization of Splitting Procedure:",
  subHeadingDescription6: `Start the dividing procedure by uploading the file our Split Pdf Tool automatically initiate it’s actions. Your request will be processed quickly by our technology, which will split the PDF into the designated sections.`,
  subHeading7: "Get Divided PDFs Here:",
  subHeadingDescription7: `After the division is finished, download each of the separate PDF sections. Your files are now perfectly divided and simple to distribute and maintain.`,
};
export const REMOVE_TOOL_PROPS = {
  backgroundImage: "/img/Rectangle22.png",
  logoImage: "/img/remove.png",
  toolName: "Remove Pages",
  toolSpec: " Remove Pages",
  bgColor: "bg-[#FDF8E1]",
  apiEndpoint: "/api/removePdf",
  BtnName: "Select PDF File",
  acceptedFiles: "application/pdf",
  Title: "Exclusion Tool - Simplifying PDF Content Organization",
  Description: `Welcome to Remove Pages Tool by DevAxon, your premier destination for state-of-the-art SEO utilities. Within our suite of tools, the Page Exclusion feature emerges as a revolutionary solution for managing PDF content. If you've encountered challenges with undesirable pages in your PDFs, our tool provides the ideal remedy.`,
  Img1: "/img/Remove1.png",
  Heading1: "Why Choose Remove Pages PDF Tool?",
  Description1: `Are you sick of stumbling over bulky PDFs that are jam-packed with pointless or needless pages? Our Remove Pages PDF Tool by DevAxon is a powerful tool for optimizing your document management workflow.`,
  Img2: "/img/Remove2.png",
  Heading2: "Principal Elements:",
  subHeading1: "Streamlined Page Removal:",
  subHeadingDescription1: `Our Remove Pages tool simplifies the elimination of undesired pages from your PDFs. Whether it's redundant data, blank pages, or specific sections earmarked for exclusion, this tool offers a rapid and efficient solution.`,
  subHeading2: "Live Preview Functionality:",
  subHeadingDescription2: `Concerned about mistakenly removing the wrong pages? Our tool incorporates a live preview feature. Prior to finalizing removals, users can preview selected pages to ensure accuracy.`,
  subHeading3: "Document Quality Preservation:",
  subHeadingDescription3: `The removal of pages should not compromise the overall quality of your PDF. Our tool guarantees the preservation of document integrity, maintaining formatting, image quality, and text presentation throughout the removal process.`,
  subHeading4: "User-Friendly Interface:",
  subHeadingDescription4: `Navigating through our tool is straightforward. With an intuitive user interface, selecting pages for removal is a seamless process suitable for both novices and experienced users. After deleting the pages the new PDF is ready for download.`,
  Img3: "/img/Remove3.png",
  Img4: "/img/Remove4.png",
  Heading3: "How to Utilize Our Remove Pages Tool?",
  subHeading5: "Put Your PDF File Here:",
  subHeadingDescription5: `Begin by uploading the PDF document from which you wish to remove pages. Our tool accommodates various file sizes, providing flexibility for diverse user needs.`,
  subHeading6: "Select Pages for Exclusion:",
  subHeadingDescription6: `Navigate through the document and pinpoint the pages slated for removal. Whether a single page, a specific range, or multiple selections are desired, our tool caters to individual requirements.`,
  subHeading7: "Download The Removed Pages File:",
  subHeadingDescription7: ` Once removed the pages, get the refined PDF file. You are now prepared to
  download the latest PDF file.`,
};
export const MERGE_TOOL_PROPS = {
  backgroundImage: "/img/Rectangle23.png",
  logoImage: "/img/Merge.png",
  toolName: "Merge Pdf",
  toolSpec: " Merge PDF",
  bgColor: "bg-[#FDE1E1]",
  apiEndpoint: "/api/mergePdf",
  BtnName: "Select PDF File",
  acceptedFiles: "application/pdf",
  Title: " Seamlessly Merge PDFs with Our Advanced Tool",
  Description: `Introducing Merge PDF Tool by DevAxon, your one-stop shop for state-of-the-art SEO tools. We're thrilled to present our Merge PDF Tool today a feature-rich solution that can streamline your document management workflow and improve the effectiveness of your website.`,
  Img1: "/img/Merge1.png",
  Heading1: "Why Merge PDFs?",
  Description1: `Managing several PDF files may be a laborious process that can cause confusion and even annoyance. The easiest way to combine many documents into a single, unified file that works for both content writers and website users is using our Merge PDF tool.`,
  Img2: "/img/Merge2.png",
  Heading2: "Key Features:",
  subHeading1: "Effortless PDF Merging:",
  subHeadingDescription1: ` Our application provides an easy-to-use method for merging numerous PDF files. Bid farewell to the headache of handling several papers and welcome to a single, well-organized solution.`,
  subHeading2: "Drag-and-drop Interface:",
  subHeadingDescription2: ` Simplicity is what we value. Combining PDFs is as simple as choosing the files you wish to combine and dragging them into the appropriate location thanks to our user-friendly drag-and-drop interface. Technical know-how is not necessary.`,
  subHeading3: "Adaptable Layout:",
  subHeadingDescription3: `Arrange your combined PDFs in a way that best fits your requirements. With the help of Merge PDF Tool, you can easily reorder pages so that the final document has the content in the order you want it.`,
  subHeading4: "Preservation of Document Quality:",
  subHeadingDescription4: `You can be confident that during the combining process, our Merge PDF tool will preserve the quality of your documents. Your material will appear in the combined file exactly as polished and professional as it does in each of the separate PDFs.`,
  Img3: "/img/Merge3.png",
  Img4: "/img/Merge4.png",
  Heading3: "How to Use Our Merge PDF Tool?",
  subHeading5: "Put Your PDF Files Online:",
  subHeadingDescription5: `Choose the PDF files you wish to combine first. Our application may be used for any size project because it supports a wide range of file sizes.`,
  subHeading6: "Sort the Files:",
  subHeadingDescription6: `Drag & drop the files into the correct sequence using the interface. Make adjustments to the layout to guarantee that the finished product reads well.`,
  subHeading7: "Get the Combined PDF here:",
  subHeadingDescription7: `After the merging process is finished, get the combined PDF file. Now you have a single, easily manageable document that you can distribute.`,
};
export const COMPRESS_TOOL_PROPS = {
  backgroundImage: "/img/Rectangle25.png",
  logoImage: "/img/Compress.png",
  toolName: "Compress Pdf",
  toolSpec: " Compress PDF",
  bgColor: "bg-[#EAEFF0]",
  apiEndpoint: "/api/compressPdf",
  BtnName: "Select PDF File",
  acceptedFiles: "application/pdf",
  Title: "Unlock Efficiency with Our Compress PDF Tool",
  Description: `Introducing SEO Tools by DevAxon, where we provide you an array of
  potent SEO tools to improve your online experience. We are excited
  to present our Compress PDF tool today a feature rich solution
  designed to improve the overall efficiency of PDF files and expedite
  file management procedures.`,
  Img1: "/img/Compress3.png",
  Heading1: "Why Do PDFs Get Compressed?",
  Description1: `Performance issues with websites can often be caused by large PDF
  files. This problem is addressed by our Compress PDF tool, which
  provides a rapid and effective method of reducing the total size
  of the PDF.`,
  Img2: "/img/Compress2.png",
  Heading2: "Principal Elements:",
  subHeading1: "Quick and Effective Compression:",
  subHeadingDescription1: ` Our program uses innovative algorithms to minimize your PDF files
  in a timely and effective manner. Reduction in file size can be
  enjoyed without compromising the papers visual integrity.`,
  subHeading2: "User-Friendly Interface:",
  subHeadingDescription2: ` We are aware of how crucial simplicity is. Even for individuals
  with little technical experience, our tools user-friendly
  interface makes the compression procedure process simple.`,
  subHeading3: "Levels of Customized Compression:",
  subHeadingDescription3: ` Adjust the compression to meet your unique requirements. Using our
  tool, you can select from a variety of compression levels that
  strike a balance between reducing file size and maintaining
  document quality.`,
  subHeading4: "Private and Secure:",
  subHeadingDescription4: `We take the confidentiality of your data very seriously. You may
  be comfortable knowing our Compress PDF utility respects your
  privacy to the fullest extent possible and keeps your documents
  private during the file compression procedure.`,
  Img3: "/img/Compress4.png",
  Img4: "/img/Compress1.png",
  Heading3: "How to Utilize Our PDF Compressor?",
  subHeading5: "Put Your PDF File Here:",
  subHeadingDescription5: ` Choose the PDF file that you want to compress first. Both tiny and
  large documents may be accommodated by our program, which supports
  a wide variety of file sizes.`,
  subHeading6: "Start Compression:",
  subHeadingDescription6: ` After configuring the parameters, begin the compression procedure.
  In little time at all, our program will perform its magic and
  provide you an optimized copy of your PDF file.`,
  subHeading7: "Download The Compressed File:",
  subHeadingDescription7: ` Once compressed, get the refined PDF file. You are now prepared to
  replace the cumbersome original with the more refined, more
  efficient variant.`,
};
export const WORD_TOOL_PROPS = {
  backgroundImage: "/img/Rectangle26.png",
  logoImage: "/img/WORD.png",
  toolName: "Word To Pdf",
  toolSpec: " Word To PDF",
  bgColor: "bg-[#EEE6FF]",
  apiEndpoint: "/api/wordToPdf",
  BtnName: "Select Word File",
  acceptedFiles:
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  Title:
    "Document Conversion Tool - Simplifying the Transition from Word to PDF",
  Description: `Greetings from SEO Tools by DevAxon, the premier source for state-of-the-art SEO solutions. Our Word To PDF Tool is a standout tool in our utility package, providing a smooth way to convert Word documents to PDFs. Say goodbye to compatibility problems and welcome the simplicity of document converting.`,
  Img1: "/img/Word1.png",
  Heading1: "Why use document conversion?",
  Description1: `Word documents can be converted to PDF format for a variety of advantages, such as enhanced security features like password protection and restricted editing, preservation of original formatting, reduced file size for easy sharing, and embedding of fonts and images for consistent visual presentation.`,
  Img2: "/img/Word2.png",
  Heading2: "Important characteristics:",
  subHeading1: "Easy Document Conversion:",
  subHeadingDescription1: `Converting your Word documents to PDF format is made simple and efficient with our Word to PDF Conversion Tool. With only a few clicks, the tool guarantees a seamless transition while working with reports, resumes, or other document kinds.`,
  subHeading2: "Preserving the Original Formatting:",
  subHeadingDescription2: `Are you worried that the formatting may change throughout the converting process? You can relax! Our application is designed to maintain the same layout, typefaces, and formatting, so your PDF will have the same visual quality as the Word document.`,
  subHeading3: "File Size Optimization:",
  subHeadingDescription3: `A complete Word to PDF converter should include file size optimization capabilities to effectively minimize the size of the generated PDF while preserving a suitable level of quality. This includes options for text and content optimization, subsetting fonts, switching color spaces, altering resolution, and compressing pictures and converting them to more efficient forms.`,
  subHeading4: "Intuitive Interface:",
  subHeadingDescription4: `Using our document conversion tool is simple and straightforward. All skill levels may utilize the user-friendly interface, which makes the converting process simple and approachable.`,
  Img3: "/img/Word3.png",
  Img4: "/img/Word4.png",
  Heading3: "How to Utilize Our Word to PDF?",
  subHeading5: "Upload Your Word Document:",
  subHeadingDescription5: `Upload your Word document to the converter to get started. Our technology is flexible enough to handle diverse document difficulties since it can handle a range of file sizes.`,
  subHeading6: "Initialization of conversion procedure:",
  subHeadingDescription6: `When you upload the word document, watch how our utility quickly converts your Word document to a PDF. The procedure is quick, easy, and ensures that the final PDF preserves the original file's quality.`,
  subHeading7: "Grab Your PDF Here:",
  subHeadingDescription7: `After the conversion is finished, just download your newly produced PDF. It is prepared for distribution, archiving, or use as required.`,
};
export const CSV_TOOL_PROPS = {
  backgroundImage: "/img/Rectangle32.png",
  logoImage: "/img/Group 32.png",
  toolName: "CSV To Pdf",
  toolSpec: " CSV To PDF",
  bgColor: "bg-[#E9F4E5]",
  apiEndpoint: "/api/anythingToPdf",
  fileType: "CSV",
  BtnName: "Select CSV File",
  acceptedFiles: ".csv",
  Title:
    "Introducing the Ultimate CSV to PDF Tool for Seamless Data Conversion",
  Description: `Professionals in a variety of sectors need to be able to switch between numerous file formats with ease in today's digital environment. Our SEO Tools Website by DevAxon is thrilled to present a state-of-the-art "CSV to PDF" conversion tool in response to this requirement. Specifically developed to facilitate the conversion of Comma-Separated Values (CSV) files into the Portable Document way (PDF), this program meets the needs of financial experts, data analysts, and anybody else who needs to display tabular data in a more professional and readable way.`,
  Img1: "/img/Remove1.png",
  Heading1: "Transforming CSV Files into Professional PDF Documents",
  Description1: `A common format for storing tabular data is provided by CSV files, which are essential to data administration. However, because CSVs require specialist software to display properly and have a plain text layout, they can be difficult to distribute and present. These issues are resolved when you convert your CSV files to PDFs. This produces a flexible document that can be seen and shared on any device without the need for specific software, all while maintaining the organized arrangement of your data.`,
  Img2: "/img/Remove2.png",
  Heading2: "Features and Benefits of Our CSV-to-PDF Converter",
  subHeading1: "Simplified Method of Conversion:",
  subHeadingDescription1: `With only a few clicks, users may convert CSV files into PDFs thanks to our tool, which streamlines the conversion process. The conversion procedure can be effortlessly navigated by users even with limited technical skills because of its easy design.`,
  subHeading2: "Sustaining data integrity:",
  subHeadingDescription2: `The guarantee that the structure and integrity of your data are maintained is one of the main benefits of utilizing our converter. Ensuring the correctness and legibility of intricate datasets during the conversion from CSV to PDF is crucial.`,
  subHeading3: "Quick Conversion Rate:",
  subHeadingDescription3: `Since time is often of the essence, our tool's rapid conversion capabilities let you convert large files without having to wait a long time.`,
  subHeading4: "Strengthened Security Protocols:",
  subHeadingDescription4: `Data security is our top priority. Because the conversion process is encrypted, you can be sure that your private information is kept safe and secure from prying eyes.`,
  Img3: "/img/Remove3.png",
  Img4: "/img/Remove4.png",
  Heading3: "Step-by-Step Guide to Converting CSV Files to PDF",
  subHeading5: "Navigate to the Converter:",
  subHeadingDescription5: `Start your adventure by locating the "CSV to PDF" converter tool on our SEO Tools page. This program makes file conversions possible anywhere, at any time, and is easy to use from any internet-connected device.`,
  subHeading6: "Mount the CSV file online:",
  subHeadingDescription6: `To add the CSV file you wish to convert, find the upload box on the tool's website. You have two options for selecting the file: drag and drop the file straight into the tool, or use a regular file picker. Various file sizes are supported by our platform, which may accommodate different data sets.`,
  subHeading7: "Get the Updated PDF Here:",
  subHeadingDescription7: `When the conversion is finished, you will be able to access your PDF file by clicking on the button. After creating a PDF, click to store it on your device, where it will be available for future use.`,
};
export const TXT_TOOL_PROPS = {
  backgroundImage: "/img/Rectangle33.png",
  logoImage: "/img/Group33.png",
  toolName: "TXT To Pdf",
  toolSpec: " TXT To PDF",
  bgColor: "bg-[#D2F6FC]",
  apiEndpoint: "/api/anythingToPdf",
  fileType: "TXT",
  BtnName: "Select TXT File",
  acceptedFiles: "text/plain",
  Title: "Streamline Your Documents: The Essential TXT to PDF Converter",
  Description: `When it comes to digital documentation, flexibility and adaptation are essential for making sure that your material is readable and displayed correctly on all devices. Taking note of this, our SEO Tools website by DevAxon is pleased to present a special "TXT to PDF" converter. This tool's clever design allows it to convert plain text files into professional-quality PDF documents, meeting the demands of academics, professionals, and everyone in between who wants a quick and easy conversion procedure.`,
  Img1: "/img/Remove1.png",
  Heading1: "Why Convert TXT to PDF?",
  Description1: `PDFs are unique in that they work with every device or piece of software and exhibit data consistently. Because of this, PDF is the preferred format for official documents, reports, e-books, and other information where it's important to preserve the original style and layout. Our TXT to PDF application makes sure your papers are prepared for distribution, presentation, or preservation by bridging the gap between the straightforward appearance of text files and the elegant, professional look of PDFs.`,
  Img2: "/img/Remove2.png",
  Heading2: "Features of Our TXT to PDF Converter",
  subHeading1: "Friendly Conversion for Users:",
  subHeadingDescription1: `Because of the user-friendly design of our program, converting TXT files to PDFs is a simple process. Your content may be easily converted into a usable PDF document with only a few clicks thanks to the simple conversion procedure.`,
  subHeading2: "Maintaining Text Integrity:",
  subHeadingDescription2: `We recognize how crucial it is to preserve your text's original layout and organization. Our converter makes sure that the layout and quality of your material are maintained as it is converted to PDF, protecting the integrity of your original document.`,
  subHeading3: "Secure Processing:",
  subHeadingDescription3: `Our first concerns are protecting your privacy and the security of your papers. Your files will always stay private thanks to the safe management of the conversion process.`,
  subHeading4: "Convenience and Accessibility:",
  subHeadingDescription4: `Our web-based TXT to PDF converter lets you convert files without requiring software downloads or installs because it is available 24/7 and can be accessed from any location.`,
  Img3: "/img/Remove3.png",
  Img4: "/img/Remove4.png",
  Heading3: "How to Use the TXT to PDF Converter Tool",
  subHeading5: "Access the Converter:",
  subHeadingDescription5: `Start by going to the "TXT to PDF" converter tool on our SEO Tools website. You don't need to download or install this program in order to use it, you can begin converting right immediately on any device. You can use it straight from your web browser.`,
  subHeading6: "Put Your TXT File Here:",
  subHeadingDescription6: `You may upload the TXT file you want to convert once you're on the tool's website. You can drag and drop your TXT file into the appropriate spot, or click to explore the directories on your device and choose the file. Regardless of its length, our program can handle files of different sizes, so you can be sure that your document is prepared for conversion.`,
  subHeading7: "Download Your PDF:",
  subHeadingDescription7: `The program will provide you a link to download your new PDF document when the conversion is finished. To save the PDF file to your device, click the download button. After that, you may inspect it to make sure it fulfills your requirements and is prepared for submission, sharing, or archiving, among other next actions.`,
};
export const EXCEL_TOOL_PROPS = {
  backgroundImage: "/img/Rectangle34.png",
  logoImage: "/img/Excel.png",
  toolName: "Excel To Pdf",
  toolSpec: " Excel To PDF",
  bgColor: "bg-[#D8EFDE]",
  apiEndpoint: "/api/anythingToPdf",
  fileType: "EXCEL",
  BtnName: "Select Excel File",
  acceptedFiles: ".xls, .xlsx, application/vnd.ms-excel",
  Title:
    "Excel to PDF: Enhancing Your Document Management with Seamless Conversion",
  Description: `The capacity to convert documents between different formats is essential in the fast-paced digital world of today. The Excel to PDF by DevAxon converter is one of the many accessible conversion tools that are very useful, effective, and easy to use. This article explores the value of the Excel to PDF tool, describing its features, advantages, and uses in a range of work-related contexts.`,
  Img1: "/img/Remove1.png",
  Heading1: "Unveiling the Excel to PDF Tool",
  Description1: `The Excel to PDF converter is specialized software that makes it simple and accurate to convert Excel files into PDF format. This utility serves users who need a dependable way to save, distribute, or print spreadsheet data in a format that is widely used. The formatting and style of your work are preserved in PDFs, as opposed to editable Excel files, so content integrity and uniformity in presentation are guaranteed across all platforms and devices.`,
  Img2: "/img/Remove2.png",
  Heading2: "Key Features and Benefits",
  subHeading1: "Preservation of Layout and Formatting:",
  subHeadingDescription1: `Throughout the conversion process, the program makes sure that all visual components—such as tables, charts, and text formatting—are kept intact. Professionals who depend on precise data representation in reports and presentations must have this functionality.`,
  subHeading2: "Enhanced protection:",
  subHeadingDescription2: `Adding a degree of protection, Excel files are converted to PDF format. Encrypted, password-protected, and editing-limited PDFs make them a safer option for distributing confidential data.`,
  subHeading3: "Universal Compatibility:",
  subHeadingDescription3: `The fact that PDF files are widely used and can be seen on any device without the need for additional software makes it easier to share documents with stakeholders, clients, and coworkers.`,
  subHeading4: "Easier Sharing and Printing:",
  subHeadingDescription4: `PDFs make it easier to share and print documents since they solve compatibility problems and guarantee uniformity, which is frequently necessary in work environments.`,
  Img3: "/img/Remove3.png",
  Img4: "/img/Remove4.png",
  Heading3: "Comprehensive Guide to Using the Excel to PDF Conversion Tool",
  subHeading5: "Launch the Tool:",
  subHeadingDescription5: `Go to the website where the Excel to PDF converter is hosted to get started. Make sure the platform you're utilizing is trustworthy, and safe, and ensures the integrity and privacy of your data. The majority of tools are handy and easy to use because they can be accessed through web browsers and don't require the installation of extra software.`,
  subHeading6: "Put Your Excel File Online:",
  subHeadingDescription6: `Once on the platform, select the Excel file upload option. Usually, a straightforward drag-and-drop interface or "Upload" button is used to do this. Choose the Excel file on your device that you want to convert. The program gives you versatility in file management by supporting several Excel file versions, such as.xls and.xlsx.`,
  subHeading7: "Get Your Document in PDF Format:",
  subHeadingDescription7: `The program will provide you with a link to download your new PDF document once the conversion is complete. To save the PDF file to the location of your choice on your device, click the download link or button.`,
};
export const PPT_TOOL_PROPS = {
  backgroundImage: "/img/Rectangle35.png",
  logoImage: "/img/Ppt.png",
  toolName: "PPT To Pdf",
  toolSpec: " PPT To PDF",
  bgColor: "bg-[#FFDFDF]",
  apiEndpoint: "/api/anythingToPdf",
  fileType: "PPT",
  BtnName: "Select PPT File",
  acceptedFiles: "application/vnd.ms-powerpoint",
  Title: "Unlocking Efficiency with the PPT to PDF Conversion Tool by DevAxon",
  Description: `In the current digital era, when information exchange and presentation are essential components of communication, there is an increased demand for dependable and effective solutions to expedite these procedures. The PPT to PDF conversion application from DevAxon is a game-changer since it provides an easy way to convert PowerPoint presentations to the commonly used PDF format. This post explores the capabilities, advantages, and unmatched ease of use of this application to make your presentations more professional, safe, and accessible.`,
  Img1: "/img/Remove1.png",
  Heading1: "Why choose DevAxon's PPT to PDF Converter?",
  Description1: `The goal of DevAxon's PPT-to-PDF application is to close the accessibility gap between dynamic presentation formats and PDF documents. The ability to quickly and easily convert PowerPoint files into PDFs may greatly improve your document handling efficiency, regardless of your role—student, professional, or business leader. This application is unique in that it provides an easy-to-use conversion procedure without sacrificing the presentation's original layout, design, or content.`,
  Img2: "/img/Remove2.png",
  Heading2: "Essential Features and Advantages",
  subHeading1: "Streamlined User Interface:",
  subHeadingDescription1: `DevAxon puts the needs of its users first, providing an easy-to-use interface that doesn't require any technical knowledge. Quick conversion of presentations to PDFs allows users to concentrate more on their content than wrangling with complicated tools.`,
  subHeading2: "Keep the content's integrity:",
  subHeadingDescription2: `This conversion tool's dedication to maintaining the original layout and caliber of your PPT files is one of its main benefits. This keeps your papers looking professional by guaranteeing that all visual components—from images to animations—are appropriately reproduced in the PDF output.`,
  subHeading3: "Comprehensive compatibility:",
  subHeadingDescription3: `Because PDFs work with nearly every kind of device and operating system, you can be sure that your audience can access your papers no matter what kind of technology they use. The frequent obstacles connected with sharing PPT files—which may require particular software to view correctly—are eliminated by this universal accessibility.`,
  subHeading4: "Eco-Friendly Resolution:",
  subHeadingDescription4: `Accepting PDFs for your presentations helps to save the environment while also streamlining your workflow. Digital documents lessen the need for hard copies, reducing the amount of paper used and encouraging a more environmentally friendly method of document management.`,
  Img3: "/img/Remove3.png",
  Img4: "/img/Remove4.png",
  Heading3:
    "Step-by-Step Guide to Using the DevAxon PPT to PDF Conversion Tool",
  subHeading5: "Navigate to Devaxon's website:",
  subHeadingDescription5: `Start by going to the particular area of your SEO Tools website that has the DevAxon PPT to PDF application. Usually, this is located under a certain tools or conversion category. You can find the tool with ease because to the website's user-friendly style.`,
  subHeading6: "Upload Your PowerPoint Presentation:",
  subHeadingDescription6: `You will be able to submit the PowerPoint (PPT) file you want to convert as soon as you open the program. You may drag and drop your file into the appropriate section or click the "Upload" button. Several PPT and PPTX file formats are supported by our platform, guaranteeing interoperability with different Microsoft PowerPoint versions.`,
  subHeading7: "Download Your PDF File:",
  subHeadingDescription7: `The program will provide you a download link for your new PDF file when the conversion is finished. To save the PDF to the location of your choice on your computer or device, click the "Download" button. Wait times are kept to a minimum by designing the entire procedure to be rapid and effective.`,
};
export const HTML_TOOL_PROPS = {
  backgroundImage: "/img/Rectangle36.png",
  logoImage: "/img/Html.png",
  toolName: "HTML To Pdf",
  toolSpec: " HTML To PDF",
  bgColor: "bg-[#FFF4D6]",
  apiEndpoint: "/api/anythingToPdf",
  fileType: "HTML",
  BtnName: "Select HTML File",
  acceptedFiles: "text/html",
  Title: "Elevate Document Management with the HTML to PDF Conversion Tool",
  Description: `The capacity to seamlessly switch between several document formats is crucial for effective data distribution and display in the digital age. In this field, the HTML to PDF conversion tool by DevAxon is an indispensable tool for web developers, content providers, and digital marketers. This post seeks to clarify the significance of the HTML to PDF tool by showcasing its features, advantages, and suitability for a wide range of work-related situations.`,
  Img1: "/img/Remove1.png",
  Heading1: "Introduction to the HTML to PDF Tool",
  Description1: `The HTML to PDF converter is an advanced software program that converts HTML web pages into the more popular and commonly used PDF format. The preservation of web page layout, content, and visual components in a static, distributable format depends on this conversion process. The tool plays a crucial role in guaranteeing that material that is available online may be reliably shared, read, and printed on many platforms and devices.`,
  Img2: "/img/Remove2.png",
  Heading2: "Essential Features and Advantages",
  subHeading1: "Precise Content Preservation:",
  subHeadingDescription1: `Throughout the conversion process, the tool does a great job of preserving the accuracy of the web page's design, including text, graphics, and intricate layouts, making sure that the PDF version accurately reproduces the original HTML.`,
  subHeading2: "Wide Accessibility:",
  subHeadingDescription2: `By transforming HTML documents into PDFs, the material may be seen without the use of a web browser or an internet connection on any device that can open PDF files.`,
  subHeading3: "Enhanced Security:",
  subHeadingDescription3: `The HTML to PDF tool is a great option for converting private or proprietary online material since PDF files may be password-protected, encrypted, and feature digital signatures to secure critical information.`,
  subHeading4: "Simplified Sharing and Archiving:",
  subHeadingDescription4: `The application makes it simple to share, print, and archive web material, promoting efficient communication and teamwork.`,
  Img3: "/img/Remove3.png",
  Img4: "/img/Remove4.png",
  Heading3: "An in-depth Guide to Using DevAxon's HTML to PDF Conversion Tool",
  subHeading5: "Navigate to Devaxon's website:",
  subHeadingDescription5: `To begin, launch your browser and navigate to the DevAxon site. From the list of services offered, choose the HTML to PDF conversion tool. The user-friendly design of Devaxon facilitates finding the required tool with ease.`,
  subHeading6: "Enter the HTML Source:",
  subHeadingDescription6: `Enter Web Page URL or Upload HTML File: There are two main ways to define the HTML source with Devaxon. Simply type the URL of the webpage into the designated area if you're converting a live web page. As an alternative, you can pick and submit an HTML file for conversion using the upload option if you have one on your device.`,
  subHeading7: "Download and save your PDF:",
  subHeadingDescription7: `DevAxon will offer a link or button to download the freshly generated PDF file after the conversion is finished. To save the document to the location of your choice on your device, click. The utility guarantees a rapid and effective download, enabling you to utilize your PDF right away.`,
};
export const PNG_TOOL_PROPS = {
  backgroundImage: "/img/Rectangle39.png",
  logoImage: "/img/Png.png",
  toolName: "PNG To Pdf",
  toolSpec: " PNG To PDF",
  bgColor: "bg-[#FDF8E1]",
  apiEndpoint: "/api/anythingToPdf",
  fileType: "PNG",
  BtnName: "Select PNG File",
  acceptedFiles: "image/*",
  Title: "Convert Your Images Seamlessly with Our PNG to PDF Tool",
  Description: `Having trustworthy and effective file-converting tools in the digital era is more important than ever. A robust and intuitive PNG to PDF converter is now available as part of DevAxon's SEO Tools suite, catering to the needs of both experts and novice users. This article explores our advanced tool's capabilities, advantages, and usage manual.`,
  Img1: "/img/Remove1.png",
  Heading1: "Why choose our PNG-to-PDF tool?",
  Description1: `The PNG to PDF tool from DevAxon's SEO Tools is widely used since it can quickly and easily convert PNG photos into PDF files that are safe, small, and compatible with all devices. This conversion procedure is essential for professionals and people needing high-quality document presentations and effective archiving.`,
  Img2: "/img/Remove2.png",
  Heading2: "Key Features of the PNG-to-PDF Tool",
  subHeading1: "High-quality Conversion:",
  subHeadingDescription1: `During the conversion process, the program makes sure that the original PNG image's quality is maintained. This is essential for preserving documents' clarity and detail, particularly for formal presentations, portfolios, and other papers where picture quality cannot be sacrificed.`,
  subHeading2: "Secure and Confidential:",
  subHeadingDescription2: `The program makes sure that all uploaded PNG files and converted PDFs are encrypted during transmission since it recognizes the value of privacy and security. Additionally, files are automatically removed from the server after a predetermined amount of time, guaranteeing important data privacy.`,
  subHeading3: "No Software Installation Needed:",
  subHeadingDescription3: `Being an online tool, it can be accessed from any device with an internet connection without requiring the download or installation of any software. Because of its ease of use, users may execute conversions anywhere, at any time, and are not restricted to using a particular program or device ecosystem.`,
  subHeading4: "Cross-Platform Accessibility:",
  subHeadingDescription4: `This feature makes sure that users don't need to install any special operating system or software to access and utilize the tool from any device, whether it is a desktop computer, laptop, tablet, or smartphone. In today's mobile-centric environment, when customers demand flawless operation across all of their devices, cross-platform compatibility is very helpful.`,
  Img3: "/img/Remove3.png",
  Img4: "/img/Remove4.png",
  Heading3: "How to convert PNG to PDF?",
  subHeading5: "Access the tool:",
  subHeadingDescription5: `Open your web browser and navigate to the SEO Tools by DevAxon website. Locate the PNG to PDF tool from the list of available tools.`,
  subHeading6: "Upload your PNG files:",
  subHeadingDescription6: `Click on the "Upload" button or drag and drop your PNG images directly into the designated area on the tool's webpage. You can select multiple files simultaneously if you need to convert several images.`,
  subHeading7: "Download Your PDF:",
  subHeadingDescription7: `After uploading the PNG file, the tool automatically converts the file, and you will be prompted to download the PDF file(s). Click on the "Download" button to save the PDF to your device. Some tools also offer the option to directly email the PDF or share it via a link.`,
};
export const JPG_TOOL_PROPS = {
  backgroundImage: "/img/Rectangle38.png",
  logoImage: "/img/Jpeg.png",
  toolName: "JPG To Pdf",
  toolSpec: " JPG To PDF",
  bgColor: "bg-[#FDE9FD]",
  apiEndpoint: "/api/anythingToPdf",
  fileType: "JPG",
  BtnName: "Select JPG File",
  acceptedFiles: "image/*",
  Title: "Elevate Your Images: The Premier JPG to PDF Conversion Tool",
  Description: `In a time where digital documentation has become paramount, it is more important than ever to simplify and transform different file types into forms that are accessible to everyone. Acknowledging this essential requirement, our SEO Tools website by DevAxon is pleased to provide a cutting-edge "JPG to PDF" converter. This utility provides an easy-to-use way to convert JPG photographs into PDF files by carefully bridging the gap between image and document formats.`,
  Img1: "/img/Remove1.png",
  Heading1: "The Importance of Converting JPG to PDF",
  Description1: `PDFs are widely recognized for their consistent look and broad interoperability across many systems and devices. For papers to be seen and shared in their intended layout, without any inconsistencies, this format is essential. The process of converting JPG photos to PDF not only improves accessibility inside the document but also helps show visual material in a more polished manner. For people and professionals who want to combine photographs into a more distributable and manageable format, our JPG to PDF converter proves to be an indispensable resource.`,
  Img2: "/img/Remove2.png",
  Heading2: "Key Features of Our JPG to PDF",
  subHeading1: "Easy Conversion Process:",
  subHeadingDescription1: ` With only a few clicks, convert your JPG photos to PDFs and enjoy the ease. The user-friendly design of our program guarantees a hassle-free converting process without the need for technical knowledge.`,
  subHeading2: "Preservation of Quality:",
  subHeadingDescription2: ` The visual integrity of your photographs is maintained in the PDF format thanks to our conversion technology, which ensures that your images keep their quality.`,
  subHeading3: "Protected and Secret:",
  subHeadingDescription3: ` Our tool protects your privacy by making sure that every transaction is carried out as securely as possible. Your uploaded photos are processed discreetly, protecting the papers you use for work and personal use.`,
  subHeading4: "Universal Access:",
  subHeadingDescription4: ` No software needs to be installed because the tool is web-based and can be used to convert data from any device at any time.`,
  Img3: "/img/Remove3.png",
  Img4: "/img/Remove4.png",
  Heading3: "Guide to Using the JPG to PDF Conversion Tool",
  subHeading5: "Access the Tool:",
  subHeadingDescription5: `First, find the "JPG to PDF" conversion tool on our SEO Tools website. This tool is handy to use whether at home, at work, or on the go because it can be accessed from any internet-connected device.`,
  subHeading6: "Put Your JPG Pictures Online:",
  subHeadingDescription6: `Once the program is open, you will see an upload option for your JPG files. Images may be chosen from your device's storage or dropped into the appropriate spot by dragging and dropping them. Multiple pictures may be uploaded at once with our tool, enabling bulk conversions if necessary.`,
  subHeading7: "Download The Converted File:",
  subHeadingDescription7: `Once your photos are uploaded our tool automatically start's the conversion process. After that, our program will convert your JPG photos into a PDF file while preserving the excellent quality and consistency of the original photos. After the conversion is finished, a download link for your new PDF file will appear. It only has to be saved to your device in order to be used.`,
};
export const PSD_TOOL_PROPS = {
  backgroundImage: "/img/Rectangle37.png",
  logoImage: "/img/Psd.png",
  toolName: "PSD To Pdf",
  toolSpec: " PSD To PDF",
  bgColor: "bg-[#D3E9F3]",
  apiEndpoint: "/api/anythingToPdf",
  fileType: "PSD",
  BtnName: "Select PSD File",
  acceptedFiles: ".psd",
  Title: "Transform Your Designs with the PSD to PDF Conversion Tool",
  Description: `The key to an effective workflow in digital design and document management is the capacity to transform data across formats. In this context, the PSD to PDF converter becomes an indispensable tool, especially for professionals such as designers, marketers, and others who handle the design-to-dissemination process.`,
  Img1: "/img/Remove1.png",
  Heading1: "Introduction to the PSD-to-PDF Tool",
  Description1: `A specialist software solution designed to convert Photoshop (PSD) files into a more flexible and accessible PDF format is the PSD to PDF converter. It fills the void that exists between the extensively used, cross-platform PDF documents and the intricate, multilayered compositions of PSD files. This conversion tool is essential for maintaining the aesthetic integrity of designs and making sure they are prepared for distribution, printing, or storage in a format that is compatible with all devices.`,
  Img2: "/img/Remove2.png",
  Heading2: "Core Features and Advantages",
  subHeading1: "Preservation of Visual Fidelity:",
  subHeadingDescription1: `The PSD to PDF tool's ability to preserve the original design's visual intricacy and quality is one of its primary advantages. This guarantees precise conversion of colors, layouts, and visual elements to the PDF format.`,
  subHeading2: "Enhanced Shareability and Compatibility:",
  subHeadingDescription2: `One of the best things about PDF files is that they work well with a wide range of devices and operating systems. PSD to PDF conversion makes it simpler to share and collaborate, and it lets recipients read the documents without special software.`,
  subHeading3: "Security and Control:",
  subHeadingDescription3: `With the help of features like encryption, password protection, and permission settings that limit editing or printing, the utility may improve the security of converted files and preserve the material within.`,
  subHeading4: "Streamlined Printing Process:",
  subHeadingDescription4: `Converting PSD designs to PDFs ensures that the printed output will match the digital design without requiring complex adjustments or software compatibility, which can streamline the printing process.`,
  Img3: "/img/Remove3.png",
  Img4: "/img/Remove4.png",
  Heading3: "Guide to Utilizing the PSD to PDF Conversion Tool",
  subHeading5: "Select PSD to PDF Conversion Tool:",
  subHeadingDescription5: `The first step in the process is to choose a trustworthy PSD-to-PDF conversion tool. Opt for a platform that guarantees the security of your files during and after conversion. SEO Tools by DevAxon ensure the privacy and quality of the file after converting it to a PDF file.`,
  subHeading6: "Upload Your PSD File to the Conversion Tool:",
  subHeadingDescription6: `Access the conversion tool's platform and look for the option to upload your PSD file. This is usually facilitated through an "Upload" button or drag-and-drop interface. Select the PSD file from your device and upload it to the tool's server.`,
  subHeading7: "Download Your Converted PDF File:",
  subHeadingDescription7: `Once the conversion is complete, the tool will typically provide a link or button to download the newly created PDF file. Click on this to save the PDF to your preferred location on your device. Ensure you review the downloaded file for accuracy and integrity.`,
};
export const PDF_TOOL_PROPS = {
  backgroundImage: "/img/Rectangle40.png",
  logoImage: "/img/pdf-to-word.png",
  toolName: "PDF To Word",
  toolSpec: " PDF To Word",
  bgColor: "bg-[#d8edf9]",
  apiEndpoint: "/api/pdfToWord",
  BtnName: "Select PDF File",
  acceptedFiles: "application/pdf",
  Title: "Elevate Document Management with DevAxon's PDF to Word Converter",
  Description: `In the digital age, converting documents across formats is vital for effective content management. DevAxon's PDF to Word Converter is an exceptional tool that stands out in this regard. Its seamless conversion of PDF documents into editable Word formats makes it an essential tool for efficient document management. This article delves into the benefits, uses, and applications of this conversion tool, highlighting how it can significantly improve document accessibility and streamline processes.`,
  Img1: "/img/Remove1.png",
  Heading1: "Streamlined Conversion Process",
  Description1: `DevAxon's PDF to Word Converter is the ultimate tool for anyone who wants to improve their document management approach. With its efficient and user-friendly design, this application allows users to effortlessly convert PDF documents into Word files, making it easier to edit, update, and reuse information. Whether you're a professional or a student, you'll find this application to be an indispensable part of your workflow.`,
  Img2: "/img/Remove2.png",
  Heading2: "Advantages of Using DevAxon's PDF to Word Converter",
  subHeading1: "Ease of Editing:",
  subHeadingDescription1: `Converting your PDF files to Word documents is imperative for hassle-free editing and formatting. With this effortless solution, you can make necessary updates while keeping the original layout, photos, and text intact. Don't wait any longer, convert your PDFs to Word docs today!`,
  subHeading2: "Enhanced Accessibility:",
  subHeadingDescription2: `You can enhance document accessibility by converting them into Word format. Word files enable easier editing, annotating, and sharing, making collaboration across teams and platforms more efficient.`,
  subHeading3: "Time and Effort Savings:",
  subHeadingDescription3: `Stop wasting your time with manual document retyping. Convert large PDF files into Word with just a few clicks and save yourself a ton of valuable time and effort.`,
  subHeading4: "Versatile Application:",
  subHeadingDescription4: `The PDF to Word Converter is a versatile software tool that serves various functions for personal, professional, and academic purposes.`,
  Img3: "/img/Remove3.png",
  Img4: "/img/Remove4.png",
  Heading3: "How to Utilize DevAxon's PDF-to-Word Conversion Tool?",
  subHeading5: "Navigate to the Converter:",
  subHeadingDescription5: `Access the tool directly on DevAxon's SEO Tools website, conveniently located under the conversion tools section.`,
  subHeading6: "Upload your PDF:",
  subHeadingDescription6: `Select the PDF document you wish to convert. You can upload files directly from your device, ensuring a smooth start to the conversion process. After uploading the file the tool automatically starts converting the document file.`,
  subHeading7: "Download your Word Document:",
  subHeadingDescription7: `Once the conversion is complete, download the editable Word file. You can then proceed to edit, format, or repurpose the document as needed.`,
};
export const SVG_TOOL_PROPS = {
  backgroundImage: "/img/SVGBack.png",
  logoImage: "/img/SVG.png",
  toolName: "SVG To PDF",
  toolSpec: " SVG To PDF",
  bgColor: "bg-[#F7E4F7]",
  apiEndpoint: "/api/anythingToPdf",
  BtnName: "Select SVG File",
  acceptedFiles: "image/svg+xml",
  Title: "Transform Your Graphics with DevAxon's SVG to PDF Converter",
  Description: `In today's digital age, having versatile and high-quality document formats is crucial for effective communication and design. DevAxon's SVG to PDF Converter is an indispensable tool that provides a simple and efficient way to convert scalable vector graphics (SVG) into Portable Document Format (PDF). This article aims to emphasize the importance of the converter in both professional and artistic situations by highlighting its superior features, unparalleled benefits, and user-friendly interface.`,
  Img1: "/img/Remove1.png",
  Heading1: "Seamless Graphic Conversion",
  Description1: `DevAxon's SVG to PDF Converter is the ultimate solution for converting SVG files into widely accessible PDF documents. It caters to the needs of content producers, digital marketers, and graphic designers and is a reliable tool that bridges the gap between scalable vector drawings and the commonly used PDF format. With this conversion tool, you can rest assured that your visuals will look great and be accessible on a variety of devices.`,
  Img2: "/img/Remove2.png",
  Heading2: "Benefits of DevAxon's SVG-to-PDF Converter",
  subHeading1: "Universal Accessibility:",
  subHeadingDescription1: `Converting SVG files to PDFs is a must to ensure their compatibility across all platforms and devices. This guarantees that the content is easily accessible and reaches a wider audience.`,
  subHeading2: "Preserved Quality:",
  subHeadingDescription2: `Our conversion method meticulously preserves the integrity and quality of the original SVG design, ensuring that every aspect of your graphics remains intact in the PDF output.`,
  subHeading3: "Enhanced Security:",
  subHeadingDescription3: `PDF documents provide a robust and secure solution to safeguard your sensitive data and intellectual property. With advanced security features like encryption and password protection, you can be confident that your information is always protected.`,
  subHeading4: "Simplified Sharing:",
  subHeadingDescription4: `Choosing PDFs for professional printing and sharing is the most practical and secure option due to their universal compatibility.`,
  Img3: "/img/Remove3.png",
  Img4: "/img/Remove4.png",
  Heading3: "How to Use the SVG to PDF Conversion Tool",
  subHeading5: "Access the Tool:",
  subHeadingDescription5: `Find the SVG to PDF Converter on the DevAxon SEO Tools Website, located within the conversion tools section for easy access.`,
  subHeading6: "Upload Your SVG File:",
  subHeadingDescription6: `Upload the SVG file you wish to convert. The platform supports direct uploads from your device, streamlining the initial step of the conversion process.`,
  subHeading7: "Download Your PDF:",
  subHeadingDescription7: `After the conversion is complete, download the resulting PDF document. Your design is now ready for sharing, printing, or archiving in its new format.`,
};
export const PROMPS_POPULAR_PDF_TOOLS = [
  {
    bgcolor: "#e4fbfe",
    logoimage: "/img/Compress.png",
    heading: "Compress Pdf",
    img2: "/img/Group1.png",
    Link: "/compress-pdf",
  },
  {
    bgcolor: "#fde1e1",
    logoimage: "/img/Merge.png",
    heading: "Merge Pdf",
    img2: "/img/Group2.png",
    Link: "/merge-pdf",
  },
  {
    bgcolor: "#dbf3f2",
    logoimage: "/img/Split.png",
    heading: "Split Pdf",
    img2: "/img/Group3.png",
    Link: "/split-pdf",
  },
  {
    bgcolor: "#fdf8e1",
    logoimage: "/img/remove.png",
    heading: "Remove Pages",
    img2: "/img/Group4.png",
    Link: "/remove-pages",
  },
  {
    bgcolor: "#eee6ff",
    logoimage: "/img/WORD.png",
    heading: "Word to Pdf",
    img2: "/img/Group15.png",
    Link: "/word-to-pdf",
  },
  {
    bgcolor: "#fde9fd",
    logoimage: "/img/Jpeg.png",
    heading: "JPG to Pdf",
    img2: "/img/Group39.png",
    Link: "/jpg-to-pdf",
  },
  {
    bgcolor: "#d2f6fc",
    logoimage: "/img/Txt.png",
    heading: "TXT to Pdf",
    img2: "/img/Group34.png",
    Link: "/txt-to-pdf",
  },
  {
    bgcolor: "#e9f4e5",
    logoimage: "/img/Csv.png",
    heading: "CSV to Pdf",
    img2: "/img/Group18.png",
    Link: "/csv-to-pdf",
  },
  {
    bgcolor: "#d8efde",
    logoimage: "/img/Excel.png",
    heading: "Excel to Pdf",
    img2: "/img/Group35.png",
    Link: "/excel-to-pdf",
  },
  {
    bgcolor: "#d3e9f3",
    logoimage: "/img/Psd.png",
    heading: "PSD to Pdf",
    img2: "/img/Group38.png",
    Link: "/psd-to-pdf",
  },
  {
    bgcolor: "#fff4d6",
    logoimage: "/img/Html.png",
    heading: "HTML to Pdf",
    img2: "/img/Group37.png",
    Link: "/html-to-pdf",
  },
  {
    bgcolor: "#ffdfdf",
    logoimage: "/img/Ppt.png",
    heading: "PPT to Pdf",
    img2: "/img/Group36.png",
    Link: "/ppt-to-pdf",
  },
  {
    bgcolor: "#fef4d4",
    logoimage: "/img/Png.png",
    heading: "PNG to Pdf",
    img2: "/img/Group40.png",
    Link: "/png-to-pdf",
  },
  {
    bgcolor: "#dce0fc",
    logoimage: "/img/ReverseImage.png",
    heading: "Reverse Image",
    img2: "/img/ReverseImageArrow.png",
    Link: "/reverse-image-search",
  },
  {
    bgcolor: "#d8edf9",
    logoimage: "/img/pdf-to-word.png",
    heading: "PDF to Word",
    img2: "/img/Group41.png",
    Link: "/pdf-to-word",
  },
  {
    bgcolor: "#f7e4f7",
    logoimage: "/img/SVG.png",
    heading: "SVG to PDF",
    img2: "/img/SVGArrow.png",
    Link: "/svg-to-pdf",
  },
];

export const PROMPS_FREE_SEO_TOOLS = [
  {
    Heading: "Fast & Effective Conversion:",
    ImgUrl: "/img/Group6.png",
    Detail: "Our cutting-edge technology ensures that your files are converted",
  },
  {
    Heading: "No Software Installation:",
    ImgUrl: "/img/Group7.png",
    Detail:
      "Our web-based PDF converter eliminates the need for downloads or installations, allowing you to convert files hassle-free.",
  },
  {
    Heading: "24/7 Positive Feedback:",
    ImgUrl: "/img/Group8.png",
    Detail:
      "Receive comprehensive assistance whenever you require it, thanks to our 24/7 customer support.",
  },
  {
    Heading: "Cost-Effective Solutions:",
    ImgUrl: "/img/Group9.png",
    Detail:
      "Enjoy the benefits of a feature-rich PDF converter tool without breaking the bank.",
  },
  {
    Heading: "People Trust Us:",
    ImgUrl: "/img/Group10.png",
    Detail:
      "Our service has been utilized by over a billion users, streamlining their tasks with digital documents.",
  },
  {
    Heading: "Regular Updates and Support:",
    ImgUrl: "/img/Group11.png",
    Detail:
      "Our team is dedicated to providing regular updates to enhance functionality and address user needs.`",
  },
];

export const ALL_TOOLS = {
  convert_and_compress: [
    {
      UrlLink: "/compress-pdf",
      Image: "/img/Compress.png",
      Alt: "compress logo",
      LiName: "Compress PDF",
      BgColor: "hover:bg-[#185058]",
    },
  ],
  Organize: [
    {
      UrlLink: "/merge-pdf",
      Image: "/img/Merge.png",
      Alt: "Merge logo",
      LiName: "Merge PDF",
      BgColor: "hover:bg-[#f56767]",
    },
    {
      UrlLink: "/split-pdf",
      Image: "/img/Split.png",
      Alt: "Merge logo",
      LiName: "Split PDF",
      BgColor: "hover:bg-[#4bc5bc]",
    },
    {
      UrlLink: "/remove-pages",
      Image: "/img/remove.png",
      Alt: "Remove Pages logo",
      LiName: "Remove Pages",
      BgColor: "hover:bg-[#f0d54d]",
    },
  ],
  Convert_to_PDF: [
    {
      UrlLink: "/word-to-pdf",
      Image: "/img/WORD.png",
      Alt: "Word To Pdf logo",
      LiName: "Word To Pdf",
      BgColor: "hover:bg-[#a981ff]",
    },
    {
      UrlLink: "/excel-to-pdf",
      Image: "/img/Excel.png",
      Alt: "Excel To Pdf logo",
      LiName: "Excel To Pdf",
      BgColor: "hover:bg-[#3ab15b]",
    },
    {
      UrlLink: "/ppt-to-pdf",
      Image: "/img/Ppt.png",
      Alt: "PPT To Pdf logo",
      LiName: "PPT To Pdf",
      BgColor: "hover:bg-[#ff6161]",
    },
    {
      UrlLink: "/jpg-to-pdf",
      Image: "/img/Jpeg.png",
      Alt: "JPG To Pdf logo",
      LiName: "JPG To Pdf",
      BgColor: "hover:bg-[#f492f6]",
    },
  ],
};
export const Tools = [
  { Name: "Merge", Url: "/merge-pdf" },
  { Name: "Compress", Url: "/compress-pdf" },
  { Name: "Split", Url: "/split-pdf" },
];
export const Slider = [
  {
    bgColor: "bg-[#185058]",
    heading: "Everything",
  },
  {
    bgColor: "bg-[#f56767]",
    heading: "Your Life",
  },
  {
    bgColor: "bg-[#4bc5bc]",
    heading: "Education",
  },
  {
    bgColor: "bg-[#f492f6]",
    heading: "Business",
  },
  {
    bgColor: "bg-[#a981ff]",
    heading: "SEO",
  },
];
